Use async/await to properly simulate long network I/O
VerdigrisTech/datastructs-algorithms-interview-problems pull request #6
Opened 2018-01-11 21:09 UTC by AndrewJo

2018-01-11 23:33 UTC, wwc278 requested changes
I found traces of old `function` syntax and would like to standardize this file to arrow functions as much as possible. Everything else looks good.

2018-01-11 23:33 UTC, wwc278 commented on javascript/batched_queries.js
> +(async function () {
Is it possible to use arrow functions here?

2018-01-11 23:33 UTC, wwc278 commented on javascript/batched_queries.js
>  String.prototype.numberify = function (timestamp) {
Is it possible to use arrow functions here?

2018-01-12 01:03 UTC, AndrewJo commented
@wwc278 Made further changes. Take a look.

2018-01-12 02:23 UTC, wwc278 approved these changes

2018-01-12 02:23 UTC, merged